### ISSUE TITLE
Contributor integration issues/questions

### ISSUE THREAD

**Issue by j9t** [11ty/11ty-community#481]
Mixed bag after having reported two Eleventy sites (#468, #469):

1. [My author name](https://www.11ty.dev/authors/j9t/) shows up as “j9t.” I did a quick check whether full names were provided anywhere with metadata, but it seems not (not per the samples I took). Is there any way to show my full name on the author page, similar to, say, [Stephanie’s](https://www.11ty.dev/authors/5t3ph/)?

2. I have donated to Eleventy in the past, and my Twitter profile is linked from [my Open Collective profile](https://opencollective.com/j9t). On my Eleventy author page, it still reads “Not yet Supporting Eleventy on Open Collective.” Am I missing something and supporter status is only recognized for regular/recent donors, or is there something else going on?

3. Out of curiosity, the two reported sites would not show on [the leaderboard](https://www.11ty.dev/speedlify/). Is this just being updated irregularly, or is there further action needed on my end?

Thank you!

**Comment by pdehaan** [comment]
/paging @zachleat since I'm not sure how the leaderboard stuff works.

I did find https://github.com/11ty/11ty-website/blob/main/src/authors/author-pages.md which seems to say that the `{{ displayName }}` should try and use the OpenCollective name, then fallback to some version of GitHub/Twitter. But yeah, that "Not yet Supporting Eleventy on Open Collective" bit is confusing since I definitely see your name there. Although I'm not sure if these pages are updated via cron or if its still a manual process by Zach.

**Comment by j9t** [comment]
@zachleat, would you mind checking on this? The issues seem to persist.
