### ISSUE TITLE
LLODO BLOG TECH AND  FE

### ISSUE THREAD

**Issue by leminhdao12** [11ty/11ty-community#605]
### Site URL

https://llodo.com

**Comment by Snapstromegon** [comment]
Hi @leminhdao12,
at first look this seems to me like this page is build and served usign WordPress and not 11ty. I think this because:
- your page includes `<meta name="generator" content="WordPress 6.4.3" />`
- https://llodo.com/wp-admin exists
- your page includes WordPress styles
- it references a "nevo" theme (which is a WP theme)
- I can't check your source, since you didn't provide it

_If_ you're using WP to build and serve your page, this is not the correct place for it.

But if you've build the page using 11ty and e.g. use WP as a headless CMS, your submission is absolutely valid and can be added.

To be clear, this comment is not about accusing you or saying your submission isn't valid, I just want to make reasonsable sure that the pages on the "built with 11ty" page are actually built using 11ty.
