### ISSUE TITLE
Deploy again

### ISSUE THREAD

**Issue by Jak2k** [11ty/11ty-community#629]
The leaderboard seems outdated.

**Comment by Snapstromegon** [comment]
Hey @Jak2k,
yes, the leaderboards don't automatically update. @zachleat runs them infrequently (last run was March 14th 2024 and the run before that was in November 2023).
Since the runs take some time and ressources to actually do, they are not executed that frequently. Sadly you'll just have to wait for the next time the leaderboard gets updated to see recently added sites.

I know this is a frequent issue and maybe we should find a way to communicate it better as it showed up multiple times in the past (just an excerpt of the >20 cases where this happened):
- https://github.com/11ty/11ty-community/issues/552#issuecomment-1950244027
- https://github.com/11ty/11ty-community/issues/546#issuecomment-1878984879
- https://github.com/11ty/11ty-community/issues/481#issuecomment-1836751450
