### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by AlbertoPrado70** [11ty/11ty-community#736]
### Site URL

https://alprado.com/icons/

### Source code URL

https://github.com/AlbertoPrado70/IAcons

### Open Collective Username

alprado-seo

### Super Professional Business Network CTA URL

https://alprado.com/

### Super Professional Business Network Company Name

ALPRADO

**Comment by Snapstromegon** [comment]
Hi @AlbertoPrado70,
just to be sure: Is https://github.com/AlbertoPrado70/IAcons the repo for the website created at https://alprado.com/icons/ and is it created with 11ty?

I'm asking, because the repo doesn't contain anything hinting towards the usage of 11ty, but it contains an index.php. Also I can open https://alprado.com/icons/index.php, so to me it looks like the page is served using the php file in the repo and is not generated by 11ty.

**Comment by AlbertoPrado70** [comment]
> Hi @AlbertoPrado70, just to be sure: Is https://github.com/AlbertoPrado70/IAcons the repo for the website created at https://alprado.com/icons/ and is it created with 11ty?
> 
> I'm asking, because the repo doesn't contain anything hinting towards the usage of 11ty, but it contains an index.php. Also I can open https://alprado.com/icons/index.php, so to me it looks like the page is served using the php file in the repo and is not generated by 11ty.

Hey, sorry for the delay—I got a little too excited with Eleventy and ended up picking a more complicated idea for my old icon page. Ran into some issues with subdirectories and Eleventy, but I managed to sort them out, so everything's good now.
